config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :utilisateurs
  resources :kots
  resources :villes
  resources :pages

  root "pages#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kot.rb
class Kot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/utilisateur.rb
class Utilisateur < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kots_controller.rb
class KotsController < ApplicationController

    skip_before_action :verify_authenticity_token


    def new 
        @kot=Kot.new
    end


    def create
        @kot = Kot.new(kot_params)

        if @kot.save
            redirect_to @kot
        else
            render 'new'
        end

    end

    def show 
        @kot = Kot.find(params[:id])
    end
    

    private 

    def kot_params
        params.require(:kot).permit(:adresse, :description)
    end





end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index 
        
    end

    


end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController

    skip_before_action :verify_authenticity_token


    def new 
        @utilisateur=Utilisateur.new
    end

    def create
        @utilisateur = Utilisateur.new(utilisateur_params)

        if @utilisateur.save
            redirect_to @utilisateur
        else
            render 'new'
        end
    end

    def show 
    end

    private 


    def utilisateur_params
        params.require(:utilisateur).permit(:email, :firstname, :name ,:mdp)

    end



end

app/controllers/villes_controller.rb
class VillesController < ApplicationController

    def index
        @ville = params[:ville]
        @kots = Kot.all.order("created_at DESC")
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kots_helper.rb
module KotsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/views/kots/_form.html.erb
<div class="background">
    salut les cramés, ici tu peux créer ton meilleur kot et le mettre en ligne 'he oua mon ga'




<!-- test de form avec html  -->


    <form class="simple_form new_kot" id="new_kot" novalidate="novalidate" action="/kots" accept-charset="UTF-8" method="post"><input type="hidden">

            <div>
                <div>
                    <div class="input string optional kot_adresse"><label class="string optional" for="kot_adresse">Adresse</label><input class="string optional input" type="text" name="kot[adresse]" id="kot_adresse"></div>
                </div>
            </div>

            <div>
                <div>
                    <div class="input text optional kot_description"><label class="text optional" for="kot_description">Description</label><textarea class="text optional textarea" name="kot[description]" id="kot_description"></textarea></div>
                </div>
            </div>

            <input type="submit" name="commit" value="Create Kot" class="btn button is-primary" data-disable-with="Create Kot">

    </form>


    
    
</div>

app/views/kots/new.html.erb
<%= render 'form' %>

app/views/kots/show.html.erb
<div class="background">
    <div class="container-center">
        <div class="header-show-kot">
            <h1>Header-show-kot</h1>
        </div>
        <div>
            <div>
                <h1 class="center-left kot-title">@kot.type</h1>  <!--todo, ajouter ça dans la db -->
            </div>

            <div class="container-images-kot">
                images
            </div>

        </div>

        <div class="container-kot-info">
            
            <strong>adresse : <%= @kot.adresse %></strong> 
            <div>@kot.ville</div>
            
            <div>
                description : <%= @kot.description %>
            </div>
        </div>

        <hr>

        <div>
            contact proprio
        </div>

        <hr>

        <div>
            maps
        </div>
        


    </div>



</div>


<!--TODO faire le show
en gros ici ça sera l affichage du kot avec le contact vers proprio-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Anton" />  <!-- link pour Anton font family-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- TODO : nav bar -->

  
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="main-page-background">

    <div class="align-header">
        <div>
            <img src="koti.png" class="logo">
        </div>
        
        <div class="container-search-bar">
            <input class="search-bar" type="search" placeholder="Trouve ton Kot!" name="search">
        </div>

        <div>
            <%= link_to "Ajouter un logement", new_kot_path%> 
        </div>

        <div>
            <%= link_to "Connexion", new_utilisateur_path%> 
        </div>

    </div>

    


    <div class="brand-name">
        KOTI
    </div>
    <div class="center">
        <img src="image_index.png">
    </div>


    <div class="cities">
        <div class="title">
            Quelle ville te chauffe?
        </div>
    
        <div class="horizontal-scroll-wrapper squares">
            <div>
                <img src="bxl.jpg" class="resize-img"> 
                <div>
                    <%= link_to "bxl", villes_path(ville: 'bxl')  %> 
                </div>
                
            </div>
            <div>
                <img src="bxl.jpg" class="resize-img"> 
                <div>
                    <%= link_to "liege", villes_path(ville: 'liege')  %> 
                </div>
                
            </div>
            <div>
                <img src="bxl.jpg" class="resize-img"> 
                <div>
                    <%= link_to "lln", villes_path(ville: 'lln')  %> 
                </div>
            </div>
            <div>
                <img src="bxl.jpg" class="resize-img"> 
                <div>
                    <%= link_to "namur", villes_path(ville: 'namur')  %> 
                </div>
                
            </div>
            
        </div>
    </div>

    




</div>

app/views/utilisateurs/_form.html.erb
<div class="background">
    salut les cramés, ici tu peux créer créer un compte sur KotIIIII et si c'est déjà fait tu peux te connecte ! 

    <div>
        <%= simple_form_for @utilisateur do |f| %>

            <div>
                <div>
                    <%= f.input :email, input_html: {class: 'input'}%>
                </div>
            </div>

            <div>
                <div>
                    <%= f.input :firstname, input_html: {class: 'input'}%>
                </div>
            </div>

            <div>
                <div>
                    <%= f.input :name, input_html: {class: 'input'}%>
                </div>
            </div>

            <!-- Pas l'impression que ce soit correct donc a voir, la solution serait de tout faire avec html et pas de simple form for -->

            <div>
                <div class="field">
                    <%= f.label :password %>
                    <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                    <% end %><br />
                    <%= f.password_field :password, autocomplete: "off" %>
                  </div>
            </div>

            <div>
                <div class="field">
                    <%= f.label :password_confirmation %><br />
                    <%= f.password_field :password_confirmation, autocomplete: "off" %>
                  </div>
            </div>

            


            <%= f.button :submit, class: "button is-primary" %>

        <% end %>



    </div>


    
    
</div>

app/views/utilisateurs/new.html.erb
<%= render 'form' %>

app/views/utilisateurs/show.html.erb
hello, ici c'est le show de l'utilisateur juste après sa création

app/views/villes/index.html.erb
<div class="background">
    <div class="header-ville">
        fleche retour arrière à gauche de ville 
        <h1 class="title">Kots à <%= @ville %> </h1>
        filtre de recherche à droite de ville

    </div>


    

    <div class="body-ville">
        <div class="vertical-scroll">
            <% @kots.each do |kot| %>

            <div class="container-card-kot">
                
                <a href="kots/<%= kot.id %>">
                    <div class="card-kot"> 
                        
                        <strong>Adresse</strong> : <p><%= kot.adresse%> </p>
                        <strong>Description</strong> : <p><%= kot.description %></p>                 
                    </div>
                </a>  
            </div>
            <% end %>
        </div>
    </div>
    

</div>

<strong></strong>